export const DEPARTMENTS = [
    { code: '010', name: 'ACCOUNTING' },
    { code: '011', name: 'ADMINISTRATIVE STUDIES' },
    { code: '016', name: 'AFRICAN STUDIES' },
    { code: '013', name: 'AFRICAN, MIDDLE EASTERN, AND SOUTH ASIAN LANGUAGES AND LITERATURES' },
    { code: '014', name: 'AFRICANA STUDIES' },
    { code: '035', name: 'AGRICULTURAL AND NATURAL RESOURCE MANAGEMENT' },
    { code: '020', name: 'AGRICULTURE AND FOOD SYSTEMS' },
    { code: '047', name: 'ALCOHOL STUDIES' },
    { code: '050', name: 'AMERICAN STUDIES' },
    { code: '067', name: 'ANIMAL SCIENCE' },
    { code: '070', name: 'ANTHROPOLOGY' },
    { code: '074', name: 'ARABIC LANGUAGES' },
    { code: '078', name: 'ARMENIAN' },
    { code: '080', name: 'ART' },
    { code: '081', name: 'ART' },
    { code: '082', name: 'ART HISTORY' },
    { code: '090', name: 'ARTS AND SCIENCES' },
    { code: '098', name: 'ASIAN STUDIES' },
    { code: '115', name: 'BIOCHEMISTRY' },
    { code: '117', name: 'BIOENVIRONMENTAL ENGINEERING' },
    { code: '119', name: 'BIOLOGICAL SCIENCES' },
    { code: '122', name: 'Biomathematics' },
    { code: '125', name: 'Biomedical Engineering' },
    { code: '126', name: 'Biotechnology' },
    { code: '136', name: 'Business Analytics and Information Technology' },
    { code: '140', name: 'Business Law' },
    { code: '146', name: 'Cell Biology and Neuroscience' },
    { code: '155', name: 'Chemical and Biochemical Engineering' },
    { code: '158', name: 'Chemical Biology' },
    { code: '160', name: 'Chemistry' },
    { code: '165', name: 'Chinese' },
    { code: '175', name: 'Cinema Studies' },
    { code: '180', name: 'Civil and Environmental Engineering' },
    { code: '185', name: 'Cognitive Science' },
    { code: '189', name: 'Communication and Media Studies' },
    { code: '192', name: 'Communication' },
    { code: '193', name: 'Community Health Outreach' },
    { code: '195', name: 'Comparative Literature' },
    { code: '198', name: 'Computer Science' },
    { code: '202', name: 'Criminal Justice' },
    { code: '203', name: 'Dance' },
    { code: '206', name: 'Dance' },
    { code: '207', name: 'Dance Education' },
    { code: '211', name: 'Filmmaking' },
    { code: '216', name: 'Ecology, Evolution and Natural Resources' },
    { code: '219', name: 'Data Science' },
    { code: '220', name: 'Economics' },
    { code: '300', name: 'Education' },
    { code: '332', name: 'Electrical and Computer Engineering' },
    { code: '351', name: 'English - Creative Writing' },
    { code: '354', name: 'English - Film Studies' },
    { code: '355', name: 'English - Composition and Writing' },
    { code: '356', name: 'English as a Second Language' },
    { code: '358', name: 'English - Literature' },
    { code: '359', name: 'English - Theories and Methods' },
    { code: '360', name: 'European Studies' },
    { code: '364', name: 'Educational Opportunity Fund' },
    { code: '370', name: 'Entomology' },
    { code: '373', name: 'Environmental and Business Economics' },
    { code: '374', name: 'Environmental Policy, Institutions and Behavior' },
    { code: '375', name: 'Environmental Sciences' },
    { code: '377', name: 'Exercise Science' },
    { code: '381', name: 'Environmental Studies' },
    { code: '382', name: 'Entrepreneurship' },
    { code: '387', name: 'Film Studies' },
    { code: '390', name: 'Finance' },
    { code: '400', name: 'Food Science' },
    { code: '420', name: 'French' },
    { code: '440', name: 'General Engineering' },
    { code: '447', name: 'Genetics' },
    { code: '450', name: 'Geography' },
    { code: '460', name: 'Geological Sciences' },
    { code: '470', name: 'German' },
    { code: '489', name: 'Greek, Modern' },
    { code: '490', name: 'Greek' },
    { code: '501', name: 'Health Administration' },
    { code: '505', name: 'Hindi' },
    { code: '506', name: 'History - General/Comparative' },
    { code: '508', name: 'History - Africa, Asia, Latin America' },
    { code: '510', name: 'History' },
    { code: '512', name: 'History - American' },
    { code: '533', name: 'Human Resource Management' },
    { code: '535', name: 'Hungarian' },
    { code: '540', name: 'Industrial and Systems Engineering' },
    { code: '547', name: 'Information Technology and Informatics' },
    { code: '573', name: 'Environmental Planning and Design' },
    { code: '522', name: 'Ethics in Business Environment' },
    { code: '001', name: 'Exchange' },
    { code: '015', name: 'Environmental and Biological Sciences' },
    // …add any remaining ones you need…
  ];
  